# Generated by Django 4.2.4 on 2023-09-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dell_laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('core', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hplaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('core', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Infinix_phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('battery_capacity', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Redmi_phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('battery_capacity', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Techno_phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('battery_capacity', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Toshiba_laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('core', models.CharField(max_length=100)),
            ],
        ),
    ]
