# Generated by Django 4.2.4 on 2023-09-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dell_laptop',
            old_name='core',
            new_name='spec',
        ),
        migrations.RenameField(
            model_name='dell_laptop',
            old_name='type',
            new_name='storage',
        ),
        migrations.RenameField(
            model_name='hplaptop',
            old_name='core',
            new_name='storage',
        ),
        migrations.RenameField(
            model_name='toshiba_laptop',
            old_name='core',
            new_name='spec',
        ),
        migrations.RenameField(
            model_name='toshiba_laptop',
            old_name='type',
            new_name='storage',
        ),
        migrations.AddField(
            model_name='infinix_phone',
            name='space',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmi_phone',
            name='space',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techno_phone',
            name='space',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
